language: java
jdk:
- oraclejdk8
install:
# login to the environment email and password should be set on travis
- java -cp TU-Agent/contextvh-*-jar-with-dependencies.jar login.Login $email $password
script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/tygronTest.test2g -v > result.txt || echo 0
# print the test output
- cat result.txt
# if there is a test failed then the build fails
- grep "test failed:" result.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" result.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/demolish.test2g -v > resultDemolish.txt || echo 0
# print the test output
- cat resultDemolish.txt
# if there is a test failed then the build fails
- grep "test failed:" resultDemolish.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultDemolish.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/buildConstruction.test2g -v > resultBuildConstruction.txt || echo 0
# print the test output
- cat resultBuildConstruction.txt
# if there is a test failed then the build fails
- grep "test failed:" resultBuildConstruction.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultBuildConstruction.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/buildGreen.test2g -v > resultBuildGreen.txt || echo 0
# print the test output
- cat resultBuildGreen.txt
# if there is a test failed then the build fails
- grep "test failed:" resultBuildGreen.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultBuildGreen.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/handleRequest.test2g -v > resultHandleRequest.txt || echo 0
# print the test output
- cat resultHandleRequest.txt
# if there is a test failed then the build fails
- grep "test failed:" resultHandleRequest.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultHandleRequest.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/upgrade.test2g -v > resultUpgrade.txt || echo 0
# print the test output
- cat resultUpgrade.txt
# if there is a test failed then the build fails
- grep "test failed:" resultUpgrade.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultUpgrade.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_2.0.2.20160601191828.jar goal.tools.Run TU-Agent/buyLand.test2g -v > resultBuyLand.txt || echo 0
# print the test output
- cat resultBuyLand.txt
# if there is a test failed then the build fails
- grep "test failed:" resultBuyLand.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultBuyLand.txt && echo 0 || $?

