language: java
jdk:
- oraclejdk8
install:
# login to the environment email and password should be set on travis
- java -cp TU-Agent/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp goal.runtime-2.0.2-20160519.221040-with-dependencies.jar goal.tools.Run TU-Agent/test.test2g -v > result.txt || echo 0
# print the test output
- cat result.txt
# if there is a test failed then the build fails
- grep "test failed:" result.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" result.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp goal.runtime-2.0.2-20160519.221040-with-dependencies.jar goal.tools.Run TU-Agent/demolish.test2g -v > resultDemolish.txt || echo 0
# print the test output
- cat resultDemolish.txt
# if there is a test failed then the build fails
- grep "test failed:" resultDemolish.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultDemolish.txt && echo 0 || $?

# run the Goal Test with a 60s timeout
- timeout 60 java -cp goal.runtime-2.0.2-20160519.221040-with-dependencies.jar goal.tools.Run TU-Agent/buildConstruction.test2g -v > resultBuildConstruction.txt || echo 0
# print the test output
- cat resultBuildConstruction.txt
# if there is a test failed then the build fails
- grep "test failed:" resultBuildConstruction.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" resultBuildConstruction.txt && echo 0 || $?

